import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/global.css";
import Navbar from "./ui/homepage/Navbar";
import { lusitana } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Rent-A-Car",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lusitana.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
